### ISSUE TITLE
Installation on macOS systems - please check

### ISSUE THREAD

**Issue by victoraalves** [CODES-group/opyrability#3]
@jkitchin and @sanqdinh,

I have tested opyrability's installation, importing and usage on win64/linux64 sucessfully. Unfortunately, I don't have a macOS system. Does any of you do? If yes, do you mind testing the installation methods from https://github.com/CODES-group/opyrability#installation?

The `pip` one is a two-step procedure due to cyipopt's availability only on conda-forge. The `conda` "method" installs everything that is needed in a single terminal command (all is described in the link above).

Thanks in advance!

**Comment by jkitchin** [comment]
The first two seemed to work.

The last instructions did not work. Not sure if it is something that is my fault or not.
```
(base) Johns-iMac-4:~ jkitchin$ conda install -c codes-group -c conda-forge opyrability
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 161, in conda_http_errors
        yield
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 127, in repodata
        response.raise_for_status()
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/codes-group/osx-64/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 116, in wrapper
        return_value = func(*args, **kwargs)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/Users/jkitchin/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/Users/jkitchin/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/Users/jkitchin/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
        return self.__get_result()
      File "/Users/jkitchin/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/Users/jkitchin/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 366, in _load
        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 120, in repodata
        with conda_http_errors(self._url, filename):
      File "/Users/jkitchin/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 208, in conda_http_errors
        raise RepodataIsEmpty(
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 462, in __init__
        body = response.json()
      File "/Users/jkitchin/anaconda3/lib/python3.10/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /Users/jkitchin/anaconda3/bin/conda install -c codes-group -c conda-forge opyrability`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/jkitchin/anaconda3/bin/conda
             CONDA_PREFIX=/Users/jkitchin/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/jkitchin/anaconda3/bin/python
               CONDA_ROOT=/Users/jkitchin/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/local/Cellar/pyenv-virtualenv/1.2.1/shims:/Users/jkitchin/.pyenv/
                          shims:/Users/jkitchin/anaconda3/bin:/Users/jkitchin/anaconda3/condabin
                          :/usr/local/sbin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/rub
                          y/bin:/Users/jkitchin/.gem/ruby/2.6.0/bin:/usr/local/opt/openjdk/bin:/
                          Users/jkitchin/bin:/Users/jkitchin/src/q-
                          e/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/
                          sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/va
                          r/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
                          :/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/
                          var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/applein
                          ternal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/jkitchin/anaconda3
            shell level : 1
       user config file : /Users/jkitchin/.condarc
 populated config files : /Users/jkitchin/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=13.5.1=0
                          __unix=0=0
       base environment : /Users/jkitchin/anaconda3  (writable)
      conda av data dir : /Users/jkitchin/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/codes-group/osx-64
                          https://conda.anaconda.org/codes-group/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jkitchin/anaconda3/pkgs
                          /Users/jkitchin/.conda/pkgs
       envs directories : /Users/jkitchin/anaconda3/envs
                          /Users/jkitchin/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.11 Darwin/22.6.0 OSX/13.5.1
                UID:GID : 501:20
             netrc file : /Users/jkitchin/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.
```

**Comment by victoraalves** [comment]
Thanks for testing @jkitchin , looks like it's a acknowledged bug in conda https://github.com/conda/conda/issues/12995

Can you please try as [suggested over there ](https://github.com/conda/conda/issues/12995#issuecomment-1674773836)the following:

please try:
`conda config --add repodata_fns repodata.json`




If that doesn't work, a [second idea is](https://github.com/conda/conda/issues/13026#issuecomment-1694138646) 

`conda clean --all `
([this will remove all cached files that might be corrupted ](https://docs.conda.io/projects/conda/en/latest/commands/clean.html))
and please try again.

then try the command again. If none of these work, it's a issue on conda's end unfortunately.

**Comment by jkitchin** [comment]
That first recommendation seems to have worked.

**Comment by victoraalves** [comment]
Nice! It looks like a bug on conda indeed. I will create a FAQ page at the documentation to point to this kind of stuff among others that might happen. 

If you want to perform a quick test, one idea could be https://github.com/CODES-group/opyrability/blob/main/docs/examples_gallery/operability_index_shower.ipynb

You would only need to run all jupyter notebook cells.

Thanks Dr. Kitchin!

**Comment by jkitchin** [comment]
That notebook ran fine for me.

**Comment by victoraalves** [comment]
In this case I will close this issue this since the installation works (even though there's a current bug in conda) for macOS systems. Thanks for testing it!
